### ISSUE TITLE
JOSM export link returns 500 error

### ISSUE THREAD

**Issue by ebenenglish** [nypl-spacetime/nypl-warper#83]
The "for JOSM" link in the Export tab returns a 500 error.

Steps to reproduce:
1. Go to the Export tab for any warped map (e.g. http://maps.nypl.org/warper/maps/7860#Export_tab)
2. Click the "for JOSM" link.

Rails log shows this error message:
```
Mapscript::MapserverError (msWMSLoadGetMapParams(): WMS server error. Unsupported SRS namespace (only EPSG and AUTO currently supported).):
  app/controllers/maps_controller.rb:776:in `OWSDispatch'
  app/controllers/maps_controller.rb:776:in `wms'
```

The link appears in the following partials:
* https://github.com/nypl-spacetime/nypl-warper/blob/master/app/views/layers/export.html.erb#L5
* https://github.com/nypl-spacetime/nypl-warper/blob/master/app/views/maps/export.html.erb#L21

Is this an actual bug, or is it intentional? The JOSM link includes a bunch of what seem like dummy params:
`srs={proj}&width={width}&height={height}&BBOX={bbox}`

Is the idea that the user is supposed to replace these when using the JOSM link?

Please advise, thanks!

**Comment by timwaters** [comment]
JOSM is a desktop editor for OpenStreetMap (and OpenHistoricalMap)
https://josm.openstreetmap.de/

The user should copy the link into the JOSM application to add that map as
a layer. The link therefore is not meant to be clicked by the user in the
browser. Ideally the system shouldn't give an error, or just not make it
clickable.

Hope this helps (I maintain timwaters/mapwarper)

**Comment by bellegis** [comment]
Hi -- at Leventhal Map we use the JOSM link to bring the maps into ArcGIS Online. For some reason the WMS link doesn't work in AGOL. It would be good if clicking for JOSM didn't give that error message.  We want to be able to teach students how to integrate our digital collections (georeferenced through map warper) with making Story Maps for class, but the for JOSM is the only one that works:

https://geo.leventhalmap.org/maps/5304#Export_tab

**Comment by timwaters** [comment]
I believe the WMS with ArcGIS Online may be due to something with CORS - as this was reported with mapwarper: https://github.com/timwaters/mapwarper/issues/165 

I don't have an arcgis online account, but i found this story map which uses the Tiles endpoint: https://www.arcgis.com/apps/StorytellingSwipe/index.html?appid=4d2c4acd2fd841588062c912f6d56d48#
